### PR TITLE
Add Bdd create test case

### PR DESCRIPTION
**Pull request by mandy-cmd**
Add bdd create test case and all steps passed. 
commands. Made VM memory larger (512 -> 1024) so that behave can run much faster. 
6m vs 1s
```
vagrant up && vagrant ssh
cp dot-env-example .env
honcho start &
behave
```
```
    Scenario: Create a recommendation                           # features/recommendations.feature:17
    Given the following recommendations                       # features/steps/recommendations_steps.py:30 0.020s
      | product_id | recommendation_product_id | relationship |
      | 1          | 10                        | UP_SELL      |
    When I visit the "Home Page"                              # features/steps/web_steps.py:35 0.053s
    And I set the "product_id" to "2"                         # features/steps/web_steps.py:52 0.082s
    And I set the "recommendation_product_id" to "7"          # features/steps/web_steps.py:52 0.074s
    And I set the "relationship" to "UP_SELL"                 # features/steps/web_steps.py:52 0.090s
    And I press the "Create" button                           # features/steps/web_steps.py:106 0.060s
    Then I should see the message "Success"                   # features/steps/web_steps.py:127 0.026s
    When I copy the "product_id" field                        # features/steps/web_steps.py:80 0.014s
    And I press the "Clear" button                            # features/steps/web_steps.py:106 0.043s
    Then the "product_id" field should be empty               # features/steps/web_steps.py:71 0.012s
    And the "recommendation_product_id" field should be empty # features/steps/web_steps.py:71 0.010s
    And the "relationship" field should be empty              # features/steps/web_steps.py:71 0.012s
    When I paste the "product_id" field                       # features/steps/web_steps.py:89 0.048s
    And I set the "recommendation_product_id" to "7"          # features/steps/web_steps.py:52 0.044s
    And I press the "Retrieve" button                         # features/steps/web_steps.py:106 0.048s
    Then I should see "UP_SELL" in the "relationship" field   # features/steps/web_steps.py:144 0.112s

1 feature passed, 0 failed, 0 skipped
2 scenarios passed, 0 failed, 0 skipped
20 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m1.179s
```

### CODE REVIEW

**Comment by procrasprincess** [comment]
do we have features and steps folders?

**Comment by mandy-cmd** [comment]
Yes they are here. 
Screen Shot 2021-07-27 at 8 09 28 PM

**Review by Aurora1024 — APPROVED** [review]
It works well. I am adding upgrade test case

**Review by procrasprincess — COMMENTED** [review]
looks good

**Comment by mandy-cmd** [comment]
> It works well. I am adding upgrade test case

I have other tests written except for the like action. Give me a sec and I'll publish those. 

I haven't written the like action tests though so if you'd like to work on that while I see if I can help with the cloud issue that'd be great. Let me get those pull requests out first though.

**Pull request merged**
