### PR TITLE
Refactor recommendation model

### PR DESCRIPTION
**Pull request by mandy-cmd**
Clarify product id in the model. Body and response now look like below instead of product_id1 and product_id2 
```
{
    "product_id" : 1,
    "recommendation_product_id" : 2,
    "relationship": "UP_SELL"
}
```

### CODE REVIEW

**Review by procrasprincess — COMMENTED** [review]
Did you run nosetests again to make sure all product_id1 and product_id2 get swapped?

**Comment by Aurora1024** [comment]
I got an error here 
1) ERROR: Clear all data entries
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/test_models.py line 177 in test_clear_data
      recommendation.create()
    service/models.py line 57 in create
      db.session.commit()
    /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py line 163 in do
      return getattr(self.registry(), name)(*args, **kwargs)
    /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py line 1046 in commit
      self.transaction.commit()
    /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py line 504 in commit
      self._prepare_impl()
    /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py line 483 in _prepare_impl
      self.session.flush()
    /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py line 2540 in flush
      self._flush(objects)
    /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py line 2682 in _flush
      transaction.rollback(_capture_exception=True)
    /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py line 68 in __exit__
      compat.raise_(
    /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py line 182 in raise_
      raise exception
    /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py line 2642 in _flush
      flush_context.execute()
    /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py line 422 in execute
      rec.execute(self)
    /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py line 586 in execute
      persistence.save_obj(
    /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py line 205 in save_obj
      for (
    /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py line 405 in _organize_states_for_save
      raise orm_exc.FlushError(
   FlushError: New instance <Recommendation at 0x7f92050f1520> with identity key (<class 'service.models.Recommendation'>, (1, 7), None) conflicts with persistent instance <Recommendation at 0x7f92050f13d0>
   -------------------- >> begin captured logging << --------------------
   flask.app: INFO: Initializing database
   faker.factory: DEBUG: Not in REPL -> leaving logger event level as is.
   flask.app: INFO: Initializing database
   flask.app: INFO: Creating Type.CROSS_SELL between 1 and 7
   flask.app: INFO: Creating Type.ACCESSORY between 1 and 7
   --------------------- >> end captured logging << ---------------------

Name                  Stmts   Miss  Cover   Missing
---------------------------------------------------
service/__init__.py      25      4    84%   30, 39-42
service/models.py        68      0   100%
service/routes.py        77      0   100%
service/status.py        46      0   100%
---------------------------------------------------
TOTAL                   216      4    98%
-----------------------------------------------------------------------------
25 tests run in 2.117 seconds. 
1 error (24 tests passed)

**Comment by mandy-cmd** [comment]
> Did you run nosetests again to make sure all product_id1 and product_id2 get swapped?



Yeah I did. 
Name                  Stmts   Miss  Cover   Missing
---------------------------------------------------
service/__init__.py      25      4    84%   30, 39-42
service/models.py        68      0   100%
service/routes.py        77      0   100%
service/status.py        46      0   100%
---------------------------------------------------
TOTAL                   216      4    98%
-----------------------------------------------------------------------------
25 tests run in 1.458 seconds (25 tests passed)

**Comment by mandy-cmd** [comment]
> I got an error here
> 
> 1. ERROR: Clear all data entries
> 
> Traceback (most recent call last):
> tests/test_models.py line 177 in test_clear_data
> recommendation.create()
> service/models.py line 57 in create
> db.session.commit()
> /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py line 163 in do
> return getattr(self.registry(), name)(*args, **kwargs)
> /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py line 1046 in commit
> self.transaction.commit()
> /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py line 504 in commit
> self._prepare_impl()
> /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py line 483 in _prepare_impl
> self.session.flush()
> /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py line 2540 in flush
> self._flush(objects)
> /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py line 2682 in _flush transaction.rollback(_capture_exception=True) /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py line 68 in **exit** compat.raise_( /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py line 182 in raise_
> raise exception
> /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py line 2642 in _flush
> flush_context.execute()
> /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py line 422 in execute
> rec.execute(self)
> /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py line 586 in execute
> persistence.save_obj(
> /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py line 205 in save_obj
> for (
> /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py line 405 in _organize_states_for_save
> raise orm_exc.FlushError(
> FlushError: New instance <Recommendation at 0x7f92050f1520> with identity key (<class 'service.models.Recommendation'>, (1, 7), None) conflicts with persistent instance <Recommendation at 0x7f92050f13d0>
> -------------------- >> begin captured logging << --------------------
> flask.app: INFO: Initializing database
> faker.factory: DEBUG: Not in REPL -> leaving logger event level as is.
> flask.app: INFO: Initializing database
> flask.app: INFO: Creating Type.CROSS_SELL between 1 and 7
> flask.app: INFO: Creating Type.ACCESSORY between 1 and 7
> --------------------- >> end captured logging << ---------------------
> 
> ## Name Stmts Miss Cover Missing
> ## service/**init**.py 25 4 84% 30, 39-42
> service/models.py 68 0 100%
> service/routes.py 77 0 100%
> service/status.py 46 0 100%
> ## TOTAL 216 4 98%
> 25 tests run in 2.117 seconds.
> 1 error (24 tests passed)

Tests all worked for me. I guess this is where I mentioned that you may need to vagrant destroy && vagrant up to clear old database though I thought that wouldn't affect tests. 

Tests are all passing for me. 

(venv) vagrant@ubuntu:/vagrant$ nosetests

Test Cases for Recommendations Model 
- Clear all data entries
- Test create a recommendation
- Delete a recommendation from the database
- Test deserialization of a Recommendation
- Test deserialization of bad data
- Test deserialization of a Recommendation with missing data
- Find a recommendation type by product id and relationship id
- Find a recommendation type by two product ids
- Test list recommendations
- Test serialization of a Recommendation
- Update a recommendation type by two product ids
- Update a recommendation type by two product ids without relationship

REST API Recommendation Server Tests 
- Delete all recommendations
- Create a new recommendation
- Create a Recommendation with missing data
- Create a Recommendation with no content type
- Delete a recommendation
- Get a single Recommendation
- Get a Recommendation thats not found
- Test index call
- Get a list of recommendations
- Query recommendations for a specific id and type
- Update an existing recommendation
- create a Recommendation with no content type
- update a Recommendation that is not found

Name                  Stmts   Miss  Cover   Missing
---------------------------------------------------
service/__init__.py      25      4    84%   30, 39-42
service/models.py        68      0   100%
service/routes.py        77      0   100%
service/status.py        46      0   100%
---------------------------------------------------
TOTAL                   216      4    98%
-----------------------------------------------------------------------------
25 tests run in 1.458 seconds (25 tests passed)

**Comment by mandy-cmd** [comment]
In any case this pull request isn't really essential to hw1 submission but just for refactoring and clarifying inputs.

**Comment by Aurora1024** [comment]
> > I got an error here
> > 
> > 1. ERROR: Clear all data entries
> > 
> > Traceback (most recent call last):
> > tests/test_models.py line 177 in test_clear_data
> > recommendation.create()
> > service/models.py line 57 in create
> > db.session.commit()
> > /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py line 163 in do
> > return getattr(self.registry(), name)(*args, **kwargs)
> > /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py line 1046 in commit
> > self.transaction.commit()
> > /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py line 504 in commit
> > self._prepare_impl()
> > /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py line 483 in _prepare_impl
> > self.session.flush()
> > /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py line 2540 in flush
> > self._flush(objects)
> > /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py line 2682 in _flush transaction.rollback(_capture_exception=True) /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py line 68 in **exit** compat.raise_( /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py line 182 in raise_
> > raise exception
> > /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py line 2642 in _flush
> > flush_context.execute()
> > /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py line 422 in execute
> > rec.execute(self)
> > /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py line 586 in execute
> > persistence.save_obj(
> > /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py line 205 in save_obj
> > for (
> > /home/vagrant/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py line 405 in _organize_states_for_save
> > raise orm_exc.FlushError(
> > FlushError: New instance <Recommendation at 0x7f92050f1520> with identity key (<class 'service.models.Recommendation'>, (1, 7), None) conflicts with persistent instance <Recommendation at 0x7f92050f13d0>
> > -------------------- >> begin captured logging << --------------------
> > flask.app: INFO: Initializing database
> > faker.factory: DEBUG: Not in REPL -> leaving logger event level as is.
> > flask.app: INFO: Initializing database
> > flask.app: INFO: Creating Type.CROSS_SELL between 1 and 7
> > flask.app: INFO: Creating Type.ACCESSORY between 1 and 7
> > --------------------- >> end captured logging << ---------------------
> > ## Name Stmts Miss Cover Missing
> > ## service/**init**.py 25 4 84% 30, 39-42
> > service/models.py 68 0 100%
> > service/routes.py 77 0 100%
> > service/status.py 46 0 100%
> > ## TOTAL 216 4 98%
> > 25 tests run in 2.117 seconds.
> > 1 error (24 tests passed)
> 
> Tests all worked for me. I guess this is where I mentioned that you may need to vagrant destroy && vagrant up to clear old database though I thought that wouldn't affect tests.
> 
> Tests are all passing for me.
> 
> (venv) vagrant@ubuntu:/vagrant$ nosetests
> 
> Test Cases for Recommendations Model
> 
> * Clear all data entries
> * Test create a recommendation
> * Delete a recommendation from the database
> * Test deserialization of a Recommendation
> * Test deserialization of bad data
> * Test deserialization of a Recommendation with missing data
> * Find a recommendation type by product id and relationship id
> * Find a recommendation type by two product ids
> * Test list recommendations
> * Test serialization of a Recommendation
> * Update a recommendation type by two product ids
> * Update a recommendation type by two product ids without relationship
> 
> REST API Recommendation Server Tests
> 
> * Delete all recommendations
> * Create a new recommendation
> * Create a Recommendation with missing data
> * Create a Recommendation with no content type
> * Delete a recommendation
> * Get a single Recommendation
> * Get a Recommendation thats not found
> * Test index call
> * Get a list of recommendations
> * Query recommendations for a specific id and type
> * Update an existing recommendation
> * create a Recommendation with no content type
> * update a Recommendation that is not found
> 
> ## Name Stmts Miss Cover Missing
> ## service/**init**.py 25 4 84% 30, 39-42
> service/models.py 68 0 100%
> service/routes.py 77 0 100%
> service/status.py 46 0 100%
> ## TOTAL 216 4 98%
> 25 tests run in 1.458 seconds (25 tests passed)

I didn't notice that. Everything works well now after destroy the old one

**Review by Aurora1024 — APPROVED** [review]

**Comment by mandy-cmd** [comment]
@Aurora1024 Yeah I sent message in slack channel but guess I should have put it in the pull request description to make it clear. Thanks for double checking and confirming it.

**Pull request merged**
